In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv(
    r"E:\BOLDANAYSTICSCOMPANY\PROJECT2STOCKMARKETANAYSIS\DATASET2\data\clean_analysis_utf8.csv"
)

# Show first rows
df.head()

,company,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe,sales_period,sales_value,profit_period,profit_value,stock_period,stock_value,roe_period,roe_value
0,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%,10 Years,21,10 Years,22,10 Years,15,10 Years,17
1,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%,5 Years,24,5 Years,6,5 Years,8,5 Years,14
2,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%,3 Years,17,3 Years,9,3 Years,7,3 Years,13
3,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%,TTM,43,TTM,18,1 Year,-2,Last Year,12
4,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%,10 Years,11,10 Years,9,10 Years,14,10 Years,40

In [2]:
# Create pros and cons

pros_cons = []

for _, row in df.iterrows():
    
    company = row['company']
    
    pro = ""
    con = ""

    # PRO rules
    if row['roe_value'] > 20:
        pro = "Good ROE performance"

    elif row['profit_value'] > 15:
        pro = "Strong profit growth"

    elif row['sales_value'] > 15:
        pro = "Strong sales growth"

    else:
        pro = "Stable performance"

    # CON rules
    if row['sales_value'] < 5:
        con = "Low sales growth"

    elif row['profit_value'] < 5:
        con = "Weak profit growth"

    elif row['stock_value'] < 5:
        con = "Weak stock growth"

    else:
        con = "No major issues"

    pros_cons.append([company, pro, con])

# Convert to dataframe
pros_cons_df = pd.DataFrame(
    pros_cons,
    columns=['company', 'pro', 'con']
)

# Remove duplicates
pros_cons_df = pros_cons_df.drop_duplicates('company')

# Show result
pros_cons_df.head()

     company                   pro                 con
0   HDFCBANK  Strong profit growth     No major issues
1    SBILIFE   Strong sales growth     No major issues
4        TCS  Good ROE performance     No major issues
8      WIPRO    Stable performance  Weak profit growth
15      INFY  Good ROE performance     No major issues

In [3]:
# Save pros and cons

pros_cons_df.to_csv(
    r"E:\BOLDANAYSTICSCOMPANY\PROJECT2STOCKMARKETANAYSIS\DATASET2\output\pros_cons.csv",
    index=False
)

print("Pros & Cons saved successfully!")

Pros & Cons saved successfully!